### ISSUE TITLE
Parsing only works with shorthand format

### ISSUE THREAD

**Issue by Root-Core** [miro662/kzones-config#1]
The `README.md` examples make use of `horizontal` and `vertical`, which can't be parsed.
You have to actually use `h` and `v` instead.

Works:

```toml
padding = 10

[layouts]
half = "h(1,1)"
```

Works not:

```toml
padding = 10

[layouts]
half = "horizontal(1,1)"
```

and results in:

```
Invaild pattern half: parser error:
 --> 1:1
  |
1 | horizontal(1,1)
  | ^---
  |
  = expected instruction
```

-----

By the way, I figured you can use quoted strings as keys. This allows nicer names, such as `Productivity L` etc.
This would make a great addition to the `README.md`, I think.
